config/routes.rb
Rails.application.routes.draw do
  default_url_options protocol: :https

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post 'sign_up/new_challenge', to: 'users/registrations#new_challenge', as: :new_user_registration_challenge
    post 'sign_in/new_challenge', to: 'users/sessions#new_challenge', as: :new_user_session_challenge

    post 'reauthenticate/new_challenge', to: 'users/reauthentication#new_challenge', as: :new_user_reauthentication_challenge
    post 'reauthenticate', to: 'users/reauthentication#reauthenticate', as: :user_reauthentication

    namespace :users do
      resources :passkeys, only: [:index, :create, :destroy] do
        collection do
          post :new_create_challenge
        end

        member do
          post :new_destroy_challenge
        end
      end
    end
  end

  # Defines the root path route ("/")
  root "root#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/passkey.rb
class Passkey < ApplicationRecord
  belongs_to :user

  validates :label, uniqueness: { scope: :user}
  validates :external_id, uniqueness: true
  validates :public_key, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :passkey_authenticatable, :registerable, :rememberable

  has_many :passkeys, dependent: :destroy

  def self.passkeys_class
    Passkey
  end

  def self.find_for_passkey(passkey)
    self.find_by(id: passkey.user.id)
  end
end


Devise.add_module :passkey_authenticatable,
                  model: 'devise/passkeys/model',
                  route: {session: [nil, :new, :create, :destroy] },
                  controller: 'controller/sessions',
                  strategy: true,
                  no_input: true

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/relying_party.rb
module RelyingParty
  extend ActiveSupport::Concern

  def relying_party
    return WebAuthn::RelyingParty.new(
      # This value needs to match `window.location.origin` evaluated by
      # the User Agent during registration and authentication ceremonies.
      origin: "https://devise-passkeys.test",

      # Relying Party name for display purposes
      name: "devise-passkeys-template"

      # Optionally configure a client timeout hint, in milliseconds.
      # This hint specifies how long the browser should wait for any
      # interaction with the user.
      # This hint may be overridden by the browser.
      # https://www.w3.org/TR/webauthn/#dom-publickeycredentialcreationoptions-timeout
      # credential_options_timeout: 120_000

      # You can optionally specify a different Relying Party ID
      # (https://www.w3.org/TR/webauthn/#relying-party-identifier)
      # if it differs from the default one.
      #
      # In this case the default would be "admin.example.com", but you can set it to
      # the suffix "example.com"
      #
      # id: "example.com"

      # Configure preferred binary-to-text encoding scheme. This should match the encoding scheme
      # used in your client-side (user agent) code before sending the credential to the server.
      # Supported values: `:base64url` (default), `:base64` or `false` to disable all encoding.
      #
      # encoding: :base64url

      # Possible values: "ES256", "ES384", "ES512", "PS256", "PS384", "PS512", "RS256", "RS384", "RS512", "RS1"
      # Default: ["ES256", "PS256", "RS256"]
      #
      # algorithms: ["ES384"]
    )
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/users/passkeys_controller.rb
# frozen_string_literal: true

class Users::PasskeysController < DeviseController
  include Devise::Passkeys::Controllers::PasskeysControllerConcern
  include RelyingParty

  def set_relying_party_in_request_env
    request.env[relying_party_key] = relying_party
  end
end

app/controllers/users/reauthentication_controller.rb
# frozen_string_literal: true

class Users::ReauthenticationController < DeviseController
  include Devise::Passkeys::Controllers::ReauthenticationControllerConcern
  include RelyingParty

  def set_relying_party_in_request_env
    request.env[relying_party_key] = relying_party
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  include Devise::Passkeys::Controllers::RegistrationsControllerConcern
  include RelyingParty
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  include Devise::Passkeys::Controllers::SessionsControllerConcern
  include RelyingParty

  def set_relying_party_in_request_env
    request.env[relying_party_key] = relying_party
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevisePasskeysTemplate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/root/index.html.erb
<h1>Root#index</h1>

<%= render "users/shared/links", resource_name: :user, devise_mapping: Devise.mappings[:user] %>

<h2>User details</h2>

<%= link_to "Edit User", edit_registration_path(current_user) %>
<%= link_to "View Passkeys", users_passkeys_path %>

<code>
<%= current_user.email %>
<%= current_user.webauthn_id %>
</code>

app/views/users/passkeys/_new_form.html.erb
<%= form_with(
      scope: :passkey,
      url: users_passkeys_url,
      method: :post,
      id: :"add-passkey-form",
      data: {
        "reauthentication_challenge_url": new_user_reauthentication_challenge_url,
        "reauthentication_token_url": user_reauthentication_url,
        "reauthentication_token_field_name": "passkey[reauthentication_token]",

        "challenge_url": new_create_challenge_users_passkeys_url,
        "credential_field_name": "passkey[credential]"
      }
) do |f| %>
  <h2>Add a passkey</h2>

  <fieldset>
    <button id="unlock-button" type="button"><%= image_tag("passkey-black.svg", width: "25", height: "25") %> Unlock</button>
    <%= f.text_field :reauthentication_token, readonly: true%>
  </fieldset>

  <fieldset id='new-passkey-fields' disabled>
    <table>
      <tr>
        <th><%= f.label :label %></th>
        <td><%= f.text_field :label, autofocus: "off", required: true %>
      </tr>
    </table>
    <%= f.hidden_field :credential %>

    <button type="submit"><%= image_tag("passkey-black.svg", width: "25", height: "25") %> Add passkey</button>
  </fieldset>
<% end %>


<script type="module">
  import {getReauthenticationToken} from 'passkey_reauthentication_handler'
  import {submitFormEvent} from 'registration_form'

  let unlockFormEvent = async function(event){
    let unlockButton = event.currentTarget
    let form = unlockButton.closest('form')
    await getReauthenticationToken(form)
    form.querySelector('#new-passkey-fields').removeAttribute("disabled")
  }

  document.querySelector('#unlock-button').addEventListener('click', unlockFormEvent)
  document.querySelector('#add-passkey-form').addEventListener('submit', submitFormEvent)
</script>

app/views/users/passkeys/index.html.erb
<h3>Passkeys</h3>

<table>
  <thead>
    <tr>
      <th>Label</th><th>Sign Count</th><th>Last Used At</th><th>Public Key</th><th>External ID</th><th></th>
    </tr>
  </thead>
  <tbody>
  <% current_user.passkeys.each do |passkey| %>
    <tr>
      <td><%= passkey.label %></td>
      <td><%= passkey.sign_count %></td>
      <td><%= passkey.last_used_at %></td>
      <td><pre><%= passkey.public_key %></pre></td>
      <td><pre><%= passkey.external_id %></pre></td>
      <td>
        <% if current_user.passkeys.count > 1 %>
          <%= form_with(
            model: [:users, passkey],
            method: :delete,
            class: "delete-passkey",
            data: {
              "reauthentication_challenge_url": new_destroy_challenge_users_passkey_url(passkey),
              "reauthentication_token_url": user_reauthentication_url,
              "reauthentication_token_field_name": "passkey[reauthentication_token]",
            }
          ) do |f| %>
            <%= f.hidden_field :reauthentication_token %>
            <button type="submit"><%= image_tag("passkey-black.svg", width: "25", height: "25") %>Delete</button>
          <% end %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= render "users/passkeys/new_form", resource_name: :user %>


<script type="module">
  import {getReauthenticationToken} from 'passkey_reauthentication_handler'

  let submitDeletePasskeyFormEvent = async function(event){
    event.preventDefault()
    event.stopImmediatePropagation()
    let form = event.currentTarget
    await getReauthenticationToken(form)
    form.submit()
  }

  document.querySelectorAll('.delete-passkey').forEach(form => form.addEventListener('submit', submitDeletePasskeyFormEvent))
</script>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

<% if signed_in?(resource_name) %>
  <%= button_to "Sign Out", destroy_session_path(resource_name), method: :delete %>
<% end %>